In [1]:
import unittest
import numpy as np
# Unit tests using unittest framework
#Import everything from the /src directory:
import sys
import os
sys.path.append('../src')

from core import toZX, toString, concatenate_ZX, right_pad, left_pad, symplectic_inner_product
#from group import radical, row_reduce
#from paulitools import *
from paulitools.converter import toZX as pt_toZX#, pt_toString
from paulitools.converter import toString as pt_toString
from paulitools.group import radical as radical_pt#, inner_product_pt
from paulitools.group import inner_product as inner_product_pt
from paulitools.group import centralizer as centralizer_pt
#def centralizer(paulis, reduced=False):
from util import toBinary, convert_array_type
from group import null_space, inner_product, centralizer, radical, row_reduce
"""    ker = radical(paulis, reduced=reduced)
    #print('ker',ker)
    if reduced:
        return ker @ paulis
    else:
        return ker @ paulis.row_reduce().row_space()"""

"    ker = radical(paulis, reduced=reduced)\n    #print('ker',ker)\n    if reduced:\n        return ker @ paulis\n    else:\n        return ker @ paulis.row_reduce().row_space()"

In [10]:
test_1_pt = pt_toZX(['XI', 'ZI', 'IZ'])
print(test_1_pt)
print(pt_toString(centralizer_pt(test_1_pt)))
print('Kernel')
kernel = radical_pt(test_1_pt)
print(kernel)
print('Paulis')
print(test_1_pt.row_reduce().row_space())

#print((kernel @ test_1_pt.row_reduce().row_space()))


[[0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]]
['IZ']
Kernel
[[0 1 0]]
Paulis
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [11]:
test_1 = toZX(['XI', 'ZI', 'IZ'])
#print(test_1)
kernel = radical(test_1.copy())
#print(test_1)
#print(type(kernel))
#print(type(kernel.astype(np.int8))) 
ker = convert_array_type(kernel, np.int8)
#print(kernel)
print('Kernel')
print(ker)
#print(row_reduce(test_1))
#print(test_1)
print(row_reduce(test_1))
print(toBinary(row_reduce(test_1)))#.astype(int))
ker @ toBinary(test_1)#.astype(int)



Kernel
[[0 1 0]]
[2 8 4 2]
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


array([[1, 0, 0, 0]], dtype=int8)

In [4]:
print(toString(test_1))
print(toString(test_2))
print(toString(test_3))



+XI, +ZI, +IZ


NameError: name 'test_2' is not defined

In [ ]:
#Check padding:
print(toString(right_pad(test_1, 2)))

+XI, +YI, 


In [ ]:
#Test padding:
combined13 = concatenate_ZX([test_1, test_3])
print(toString(combined13))
combined12 = concatenate_ZX([test_1, test_2])
print(toString(combined12))

+X, +Y, +Z, 
+XI, +YI, +YY, +XX, 


In [ ]:

concat = concatenate_ZX([test_1,test_3])
print(concat)
#print(convert_from_integer_representation(concat))
correct_return = toZX(['YY', 'XX','XI','YI'])
print(correct_return)


[1 4 6 2]
[ 2 30 24  8 10]


Ok. Now, I need a function that allows me to multiply Paulis. Specifically, multiplication is addition in the symplectic form, ie, binary addition. 

Make the function numba compatible, and allow feeding arrays of paulis. 

Al

In [ ]:
def transform_binary(n):
    n_bits = n.bit_length()
    m = 0
    for i in range(n_bits):
        # Read bits from the most significant bit to the least significant bit
        bit = (n >> (n_bits - i - 1)) & 1
        # Place the bit at position (2 * i + 1) in the result
        m |= bit << (2 * i + 1)
    return m

# Example usage
print(transform_binary(7))
print(int('01011',2))

#n = 0b110  # Binary integer 110
#transformed_n = transform_binary(n)
#print(bin(transformed_n))  # Output: 0b1010
#print(transformed_n)       # Output: 10


42
11


In [ ]:
X = toZX(['XX'])
XI = toZX(['XI'])
Y = toZX(['Y'])

XII = toZX(['XXI'])

#Xpadded1 = right_pad(X, 2)
Xpadded2 = right_pad(X, 3)
#print(Xpadded1)
print(Xpadded2)
print(XI)
print(XII)

#assert Xpadded1[1] == XI[1]
#assert Xpadded2 == XII

[ 3 48]
[2 8]
[ 3 48]


In [ ]:
input = toZX(['X', 'Y', 'Z', 'I', 'XX', 'IZ', 'YX'])
#print(input)
output = toZX(['XIII', 'YIII', 'ZIII', 'IIII', 'XXII', 'IZII', 'YXII', 'XYZI'])
input_pad = right_pad(input, 4)
print(input_pad)
print(output)

print(right_pad(toZX(['XX']),4))
print(toZX(['XXII']))


[ 4 32 34  2  0 96  4 98]
[  4  32  34   2   0  96   4  98 108]
[ 4 96]
[ 4 96]


In [ ]:
input1 = ['X', 'YY', 'ZZZ']
input2 = ['X', 'IY']
input3 = ['Y','XIYZ' ]
ZX1 = toZX(input1)
ZX2 = toZX(input2)
ZX3 = toZX(input3)

In [ ]:
input = toZX(['X', 'Y', 'Z', 'I', 'XX', 'IZ', 'YX'])
#print(input)
output = toZX(['IIIX', 'IIIY', 'IIIZ', 'IIII', 'IIXX', 'IIIZ', 'IIYX'])
input_pad = left_pad(input, 4)
print(input_pad)
print(output)

print(right_pad(toZX(['XX']),4))
print(toZX(['XXII']))


[  4  32  40   8   0  96  16 104]
[  4 256 272  16   0 384  16 392]
[ 4 96]
[ 4 96]


In [ ]:
String_forms = [
    ['X','Y'],
    ['XX','ZI'],
    ['XZY', 'Z']
]
output12 = ['XI','YI','XX','ZI']
output13 = ['XII', 'YII', 'XZY', 'ZII']
cat12 = concatenate_ZX((toZX(String_forms[0]), toZX(String_forms[1])))
cat13 = concatenate_ZX((toZX(String_forms[0]), toZX(String_forms[2])))
ZXoutput12 = toZX(output12)
ZXoutput13 = toZX(output13)
print(cat12)
print(ZXoutput12)
print(cat13)
print(ZXoutput13)

[ 2  8 10 24  2]
[ 2  8 10 24  2]
[ 3 16 18 92  2]
[ 3 16 18 92  2]


In [ ]:
p1 = toZX(['XX'])
p2 = toZX(['YY'])
p3 = toZX(['ZI'])

print(symplectic_inner_product(p1,p2))
print(symplectic_inner_product(p1,p3))
print(symplectic_inner_product(p2,p3))

[0]
[1]
[1]
